version: "3.6"
services:
  vault:
    image: 
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    env_file:
      - environment_vars.env
    volumes:
      - ./secrets:/secrets
